### ISSUE TITLE
Zend\Form\Form::isValid is unable to validate as there is no input filter present

### ISSUE THREAD

**Issue by ghost** [ZF-Commons/ZfcUser#118]
Stack trace:

```
#0 vendor\zf-commons\zfc-user\src\ZfcUser\Service\User.php(68): Zend\Form\Form->isValid()
#1 vendor\zf-commons\zfc-user\src\ZfcUser\Controller\UserController.php(181): ZfcUser\Service\User->register(Array()
```

**Comment by seif1993-hub** [comment]
Zend\Form\Form::isValid is unable to validate as there is no data currently set ????????
